### ISSUE TITLE
locale set overwrites an explicitly set locale with undefined

### ISSUE THREAD

**Issue by OrKoN** [n-fuse/locale-set#1]
If I set an unsupported locale, the locale becomes undefined and it does so asynchronously. 

```
    var localeSet = new EmLocaleSet(apiDoc.localeSet);
    localeSet.setProperties(localeSet.read());
```

Actual: Now localeSet.get('locale') equals whatever is set in the local storage but then after the promise in the constructor of LocaleSet is resolved the locale is undefined.

Expected: the locale equals one of the supported locales.

**Comment by Dani723** [comment]
The localeSet is not meant to be used before it is fully initialized. 
Before the supportedLocales are evaluated (e.g. with the apiDoc.localeSet uri), the state of the locale property should always be 'unknown/undefined', as even the local storage value must not match one of the supported locales.

But I'm not sure how to handle this. 
Maybe by throwing an exception, when the locale/fbLocale is set before it is initialized and making the localeSet an promise itself. 

`localeSet.then(()=>localeSet.locale='de')`

I think adding a state machine (as in token-authn) is overkill.

**Comment by OrKoN** [comment]
@Dani723 maybe you could just expose the promise? e.g. `localeSet.isReady().then(function () {
});`
