### ISSUE TITLE
The locale set is requested via http and not via the current page protocol

### ISSUE THREAD

**Issue by OrKoN** [n-fuse/locale-set#2]
Mixed Content: The page at 'https://restore.invend.eu/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://restore.invend.eu/locale_sets/default'. This request has been blocked; the content must be served over HTTPS.

I am not sure if this module loads the locale sets but it seems so

**Comment by Dani723** [comment]
Please use apiLocaleSet instead of localeSet from the apiDoc
Invend/api-doc@3b88a8c7359c44318597a88b35461ae4ca1156a8
